### ISSUE TITLE
Exercise 6 - Task 3: Making predictions with the registered models.

### ISSUE THREAD

**Issue by c-nova** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#19]
I've tried to PREDICT task with 'White listed Pool'.

```
-- Retrieve the latest hex encoded ONNX model from the table
DECLARE @model varbinary(max) = (SELECT Model FROM [wwi_mcw].[ASAMCWMLModel] WHERE Id = (SELECT Top(1) max(ID) FROM [wwi_mcw].[ASAMCWMLModel]));

-- Run a prediction query
SELECT d.*, p.*
FROM PREDICT(MODEL = @model, DATA = [wwi_mcw].[ProductPCA] AS d) WITH (prediction real) AS p;
```

But this query was return with error below:

> 11:31:44
> 
> Started executing query at Line 1
> 
> Failed to execute query. Error: Message(s) from 'PREDICT' engine: The type of model column 'f00' is 'real'. Doesn't match the input column type.
> Total execution time: 00:00:02.064

Have you any idea for resolve this issue?

**Comment by nansravn** [comment]
I'm also having the same issue here:
```
Failed to execute query. Error: Message(s) from 'PREDICT' engine: The type of model column 1 (1-based) is 'real'. Doesn't match the input column type.
Total execution time: 00:00:00.585
```

**Comment by codingbandit** [comment]
@DawnmarieDesJardins this one can be closed since we've removed this portion of the lab until PREDICT is supported.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  Thanks Carey
