### ISSUE TITLE
Additional enhancement request

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#21]
Received via email:
Do we have the opportunity to add an example to use the Azure Machine Learning SDK in Spark?  This is good for Synapse to integrate AML.

Thank you!

Mark Chen

**Comment by codingbandit** [comment]
We are currently using the Azure Machine Learning SDK to use AutoML to create a classification model. (Exercise 6 notebook) - is there additional clarification if something specific is desired ?

**Comment by DawnmarieDesJardins** [comment]
Closing as resolve with merge of PR #40
