### ISSUE TITLE
Running Powershell Script in Lab Setup

### ISSUE THREAD

**Issue by smithavenkat** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#24]
In the lab setup – we are required to run a powershell script – to set up the storage account with the needed data to go through the exercises. However, it does not seem to work the way intended. I see the containers and such created but I don’t see any data. Is this something you can help with ?

https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Azure%20Synapse%20Analytics%20and%20AI.md#task-5-run-environment-setup-powershell-script .

**Comment by codingbandit** [comment]
When you ran the setup script at the end of the Before the Hands on Lab - there is a verification step at the end of the script. Can you confirm that you saw this message: Environment validation has succeeded.

**Comment by timahenning** [comment]
@smithavenkat Hi, can you provide confirmation?  Otherwise, I have to close the issue due to lack of activity.

Thanks,

Tim

**Comment by timahenning** [comment]
Closed due to lack of activity.
