### ISSUE TITLE
Pipeline fails in Task 6

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#25]
Pipeline run fails when running Task 6 for Campaign Analytics. Error is Country is null and it fails unique constraint in DW. It looks like Dataflow is unable to correctly map undefined last two columns. When I remove skip row = 1, I see that schema is identified. But I understand whole exercise is not to enable debug.

**Comment by codingbandit** [comment]
Hi @rgknp - thank you for working through this lab! The purpose of Task 6 is to show you how to deal with malformed data coming in. It is imperative that you should follow each of the steps very closely, and you'll see how it gets transformed properly and sinked into the DW :)

**Comment by rgknp** [comment]
Thanks @codingbandit . Is there any change to csv file or only a change in instructions?

**Comment by codingbandit** [comment]
There is a change in instruction- also when testing your issue a couple of changes in Synapse today warranted some modifications to the deployment artifacts. You can see all the changes in the PR mentioned above

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #26
