### ISSUE TITLE
Output from PySpark code not matching with that of SQL Serverless

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#27]
In Exercise 3: Exploring raw parquet -> Task 2 -> Step 7

PySpark code needs changes to match output of SQL Serverless in the previous Task. For example in Serverless It is Avg Profit while in PySpark it is Avg Quantity

Updated Code here:

`from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

profitByDateProduct = (data_path.groupBy("TransactionDate", "ProductId")
.agg(
    round(sum("ProfitAmount"),2).alias("(sum)Profit"),
    round(avg("ProfitAmount"),2).alias("(avg)Profit"),
    sum("Quantity").alias("(sum)Quantity")
).orderBy("TransactionDate", "ProductId")
)
profitByDateProduct.show(100)`

**Comment by codingbandit** [comment]
Thank you for identifying this, the lab has been updated appropriately.
