### ISSUE TITLE
Running individual SQL statement do not enforce Column level security

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#28]
In Exercise 5: Security -> Task 1: Column level security -> Step 2

The script provided does not specify that in order to check column level security below 2 statements should be executed together:

EXECUTE AS USER ='DataAnalystMiami';
select TOP 100 * from wwi_mcw.CampaignAnalytics;

If I run just the select query by highlighting, I am able to see all the columns.

**Comment by codingbandit** [comment]
Updated the lab instructions to select code blocks vs individual statements. Thank you for this observation that led to adding clarity to the instructions.
