### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#29]
This lab is excellent resource to onboard internal and external Customers on Synapse Analytics. I have received some feedback through several conversations with Customers and it would be great to include exercises on below topics:

1. Delta Lake operations through Spark and SQL Serverless
2. Hive database operations through Spark and SQL Serverless
3. Using Spark/ SQL Serverless to populate Synapse tables
4. End to end security using Azure AD Managed Service Identity/Service Principal based auth. This is the top ask from Customers as no one wants to hard code SQL credentials. How do we integrate Synapse, Serverless, Spark, ADLS Gen2 and Pipelines without hard coding credentials anywhere.

**Comment by DawnmarieDesJardins** [comment]
@rgknp
Thanks Rahul!  I'm marking this issue as an enhancement for leads and SMEs to review at our next update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue to archive content.
