### ISSUE TITLE
Unable to import schema 

### ISSUE THREAD

**Issue by kreidOSS** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#31]
When Completing Task 2 - Step 6 of the HOL. I am unable to import the schema for files within wwi-02/sale-small directory when using "From connection/store".

**"An error occurred when invoking java, message: java.lang.OutOfMemoryError:Unable to retrieve Java exception. total entry:31 sun.misc.Unsafe.allocateMemory(Native Method) java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127) java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) org.apache.parquet.hadoop.codec.SnappyDecompressor.setInput(SnappyDecompressor.java:102) org.apache.parquet.hadoop.codec.NonBlockedDecompressorStream.read(NonBlockedDecompressorStream.java:46) java.io.DataInputStream.readFully(DataInputStream.java:195) java.io.DataInputStream.readFully(DataInputStream.java:169) org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:204) org.apache.parquet.column.impl.ColumnReaderImpl.readPageV1(ColumnReaderImpl.java:591) org.apache.parquet.column.impl.ColumnReaderImpl.access$300(ColumnReaderImpl.java:60) org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:540) org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:537) org.apache.parquet.column.page.DataPageV1.accept(DataPageV1.java:96) org.apache.parquet.column.impl.ColumnReaderImpl.readPage(ColumnReaderImpl.java:537) org.apache.parquet.column.impl.ColumnReaderImpl.checkRead(ColumnReaderImpl.java:529) org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:641) org.apache.parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:357) org.apache.parquet.column.impl.ColumnReadStoreImpl.newMemColumnReader(ColumnReadStoreImpl.java:82) org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:77) org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:270) org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:135) org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:101) org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:154) org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:101) org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:140) org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:214) org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:125) org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:129) com.microsoft.datatransfer.bridge.parquet.ParquetBatchReaderBridge.<init>(ParquetBatchReaderBridge.java:68) com.microsoft.datatransfer.bridge.parquet.ParquetBatchReaderBridge.open(ParquetBatchReaderBridge.java:63) com.microsoft.datatransfer.bridge.parquet.ParquetFileBridge.createReader(ParquetFileBridge.java:22) . . Activity ID: ff763d59-580a-4d9c-bcab-47bb69b3a999"**

When attempting to use "From sample file" (sale-small-20190101-snappy.parquet) I recieve the following error:

**"Schema import failed: File size exceeded the limit: 2048 Kb."**

As a workaround I have chosen "none".

**Comment by codingbandit** [comment]
I've seen this happen before, it seems to be a transient problem. If this happens, I just press 'OK' one more time and it will work.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  Please reopen if necessary.
