### ISSUE TITLE
Azure Synapse SQL pool : SKU

### ISSUE THREAD

**Issue by shkumesh** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#32]
Do we really need DW500c (sqlServerSKU) for this workshop?

https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/environment-setup/automation/00-asa-workspace-core.json

![image](https://user-images.githubusercontent.com/48082518/90410415-f4e54000-e0c7-11ea-92cd-4e4daad07127.png)

Pricing:

![image](https://user-images.githubusercontent.com/48082518/90410604-32e26400-e0c8-11ea-8b53-e04f90312f93.png)

**Comment by codingbandit** [comment]
this size was chosen as the best trade-off for performance and cost for the temporary nature of this MCW environment.

**Comment by shkumesh** [comment]
Thank you for the update.
