### ISSUE TITLE
Invalid schema name

### ISSUE THREAD

**Issue by shkumesh** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#33]
Exercise 5: Synapse Pipelines and Cognitive Search -> Task 4: Create the Synapse Pipeline -> 45

The table schema name should be: wwi_mcw (not dbo)

![image](https://user-images.githubusercontent.com/48082518/92084192-a7194900-ede4-11ea-9800-2cdafdf75293.png)

**Comment by codingbandit** [comment]
Great catch!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #37.
