### ISSUE TITLE
Invalid URL in the postman template file

### ISSUE THREAD

**Issue by shkumesh** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#34]
file: https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/environment-setup/skillset/InvoiceKnowledgeStore.postman_collection.json

There is an extra "1" in url:raw

![image](https://user-images.githubusercontent.com/48082518/92199816-c58b4d00-ee95-11ea-98bd-b5d68c716bdd.png)

**Comment by codingbandit** [comment]
Great catch!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #37.
