### ISSUE TITLE
Azure ML workspace is invalid

### ISSUE THREAD

**Issue by shkumesh** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#35]
Exercise 7: Cell 41 (Train classifier using Auto ML)

Azure ML workspace name is invalid. This has to replace with the correct workspace name.

https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/environment-setup/automation/notebooks/ASAMCW%20-%20Exercise%207%20-%20Machine%20Learning.ipynb

![image](https://user-images.githubusercontent.com/48082518/92224546-912c8680-eebf-11ea-9b9d-ee32ee95247e.png)

**Comment by codingbandit** [comment]
Great catch!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #37.
