### ISSUE TITLE
No "Dataset" option in the data blade

### ISSUE THREAD

**Issue by shkumesh** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#38]
There is no "Dataset" option in the data blade

![image](https://user-images.githubusercontent.com/48082518/92384775-511f0b00-f12e-11ea-9111-591b816c8602.png)

Lab guide:

![image](https://user-images.githubusercontent.com/48082518/92384969-a78c4980-f12e-11ea-90da-c0975accc993.png)

![image](https://user-images.githubusercontent.com/48082518/92385030-c2f75480-f12e-11ea-91a8-e6ce54ec9134.png)

**Comment by codingbandit** [comment]
Thanks @shkumesh , they have added 'integrated' in front of the dataset in the UI. The screenshots will be updated in the next update cycle.

**Comment by shkumesh** [comment]
@codingbandit thanks for the udpate

**Comment by DawnmarieDesJardins** [comment]
Closed as resolved with merger of PR #40
