### ISSUE TITLE
Exercise 5: Additional steps to be specified

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#39]
1. **Exercise 5 Task 2 step 20**
While running the file Hands-on lab/artifacts/pocformreader.py the following exception occurs for the line "quit()" and it can be ignored so we can add a note after step 20.
![image](https://user-images.githubusercontent.com/55180169/94195610-df3a1600-fed0-11ea-85af-de8f881605ca.png)

2. **Exercise 5 Task 3 step 8**
While deploying the function app the function **GetInvoiceData** is not deployed , there are additional steps to be performed in order to deploy the function as shown, and the steps are not mentioned in the guide
![image](https://user-images.githubusercontent.com/55180169/94196473-08a77180-fed2-11ea-8e19-268a583b16d0.png)

3. Azure function core tools is required for the lab but this isn't mentioned in the before hands on part

**Comment by DawnmarieDesJardins** [comment]
Closed as resolved with merge of PR #40
