### ISSUE TITLE
Getting "Permission Denied" when Running Powershell Script in Lab Setup

### ISSUE THREAD

**Issue by ewittrock-uwm** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#41]
When attempting to run the PowerShell Script that is part of the environment setup I get "Permission Denied".  

xxxxx@Azure:~/Synapse-MCW/Hands-on lab/environment-setup/automation$ ./01-environment-setup.ps1
bash: ./01-environment-setup.ps1: Permission denied

This is Task 5, Step 2 in the Before the Hand-on Lab instructions.

Thanks in advance for any assistance!

**Comment by ewittrock-uwm** [comment]
I realized I was in the Bash editor and not in the PowerShell editor.  After switching Cloud Shell to the PowerShell editor I was able to run the script.  

In the instructions for Task 3, it might be nice to specify that the PowerShell editor should be used, just to avoid this silly mistake.

**Comment by timahenning** [comment]
Thank you for the suggestion.  We will update the docs.
