### ISSUE TITLE
Error during environment setup

### ISSUE THREAD

**Issue by alexanderv21** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#46]
Hi,

I'm having this error during environment setup at this stage: https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/environment-setup/automation/environment-automation/environment-automation.psm1#L537

![image](https://user-images.githubusercontent.com/17249308/97152041-efc8ff00-17a2-11eb-92c0-7b53e2d8c905.png)

Seems its due to API endpoint issue (the version is hardcoded on line 535)?

**Comment by alexanderv21** [comment]
Update:

The notebook itself seems copied just fine though, so wondering why it returns _UnsupportedOperation_:

![image](https://user-images.githubusercontent.com/17249308/97153355-efc9fe80-17a4-11eb-864f-79181b6ce269.png)

**Comment by alexanderv21** [comment]
Just go through the code (https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/environment-setup/automation/01-environment-setup.ps1#L224), seems its only an intermittent issue. Need to confirm and close if that's the case

Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #47
