### ISSUE TITLE
cannot connect to sqlpool01 as deployed by scripts

### ISSUE THREAD

**Issue by kodaksmile** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#48]
I ran the pre HOL scripts and they completed successfully. The first create table fails as the schema does not exist.  I created the schema manually. When I try to connect to sqlpool01 via the linked service that was created under the covers it fails with the following error message:
Cannot connect to SQL Database: 'asaworkspacelg68.sql.azuresynapse.net', Database: 'SQLPool01', User: 'asa.sql.admin'. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.
Login failed for user 'asa.sql.admin'., SqlErrorNumber=18456,Class=14,State=1,
. Activity ID: 35f898aa-8ca2-4158-8dff-1397945cf8ce
This may happen if your data source only allows secured connections. If that's the case, please create a new workspace with virtual network option enabled.

I can explore sqlpool01 via the workspace under data and was able to create the table as above however I cannot create a linked service to the same SQL pool.  Testing the linked service fails.  Switching to password from AKV and typing in the password fails.  

This workshop was scheduled to be delivered to a customer next week.  One of their team has tried to run through it early and is also running into issues.

**Comment by codingbandit** [comment]
Hi @kodaksmile - I just ran through the deployment and was able to create the sale table without issue in Exercise 2, Task 1.

Could I ask what region you are using to deploy? I am wondering if there may be some transient issues at play here. Is your customer experiencing the same issue, or is it something different? Are they deploying to the same region? (I tested deploying to East US).

In the meantime I will have another team member test the deployment/creation of tables in the SQL Pool.

**Comment by kodaksmile** [comment]
Hi,
I used west us 2 as I am a CSA based in Phoenix. I’m going to run through it again tomorrow and see if I hit the same issue. I do know the SQL scripts that create the 2 logins fail as the passwords are not complex enough (tried running those directly in the SQL pool).
Regards,
Laura

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codingbandit** [comment]
Hi Laura, yes, strong passwords are required. Please retry tomorrow and let me know how it goes!

**Comment by kodaksmile** [comment]
In which case the SQL script in the SQL folder will need to be fixed.   Contents of  00_master_setup.sql:
create login [asa.sql.workload01] with password = '#PASSWORD#'
create login [asa.sql.workload02] with password = '#PASSWORD#'

Regards,

Laura

**Comment by codingbandit** [comment]
Thank you, in the meantime I will update the Before the hands on lab and further define the strong password requirements.

**Comment by codingbandit** [comment]
My pending edit adds this to Task 2 step 2 of the before the hands on lab document:

    **Note**: Password requirements are as follows:
    
       1. Your password must be between 8 and 128 characters long.
       2. Your password must contain characters from three of the following categories: English uppercase letters, English lowercase letters, numbers (0-9), and non-alphanumeric characters (!, $, #, %, etc.).
      3. Your password cannot contain all or part of the login name. Part of a login name is defined as three or more consecutive alphanumeric characters.

**Comment by kodaksmile** [comment]
Ok but, this is a script file that I *think may be run by the setup?  We may need to update the passwords coded in the file.  I didn’t see a spot that said to open and run them but, I may be wrong as I was really only looking for something to help with my issue.

Thank you very much for the quick responses!

Regards,

Laura

**Comment by codingbandit** [comment]
Hi Laura, yes you are right, the script that you found is run during the powershell setup of the workspace environment (01-environment-setup.ps1) - this script does the password replacements and automates the creation of the synapse workspace assets. This is not meant for anyone to have to do manually.

**Comment by kodaksmile** [comment]
Just a quick update – I had used a complex password yesterday and while it should successful obviously something happened that did not create some of the resources properly (the linked service to the SQLPool01 for example).  I dropped the entire resource group last night and started from scratch this morning and I have gotten past that point now (running the first data copy pipeline in exercise 2 currently) so I am guessing there was some blip yesterday that didn’t get logged.  I will let you know if I find anything else as I go through the lab.  I am also circling back to hear what the customer’s experience was when he tried to go through it.

Thank you again for the quick and timely responses.  I appreciate your support.

Regards,

Laura

**Comment by arvind-dhariwal** [comment]
Start the SQLPool01 SQL pool if needed.
Setup SQLPool01
Invoke-Sqlcmd: /home/arvind/Synapse-MCW1/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:979
Line |
 979 |  …   $result = Invoke-SqlCmd -Query $SQLQuery -ConnectionString $sqlConn …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The server principal 'asa.sql.workload01' already exists. The server principal 'asa.sql.workload02' already exists.   Msg 15025, Level 16, State 1, Procedure , Line 1.

Invoke-Sqlcmd: /home/arvind/Synapse-MCW1/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:979
Line |
 979 |  …   $result = Invoke-SqlCmd -Query $SQLQuery -ConnectionString $sqlConn …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | There is already a master key in the database. Please drop it before performing this statement.   Msg 15578, Level 16, State 1, Procedure , Line 1.

**Comment by codingbandit** [comment]
As mentioned in your other issue #49 - it looks like you have run this script more than once in the environment.

**Comment by codingbandit** [comment]
Please delete your resource group. Try re-starting the lab from the beginning

**Comment by timahenning** [comment]
Solution provided.
