### ISSUE TITLE
Empty SQL pool tables

### ISSUE THREAD

**Issue by arvind-dhariwal** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#49]
My env set up went successfully but i dont see any data in tables -

- [wwi_mcw].[ASAMCWMLModel]
-  [wwi_mcw].[Product]

I got only below error while setting env -

_Start the SQLPool01 SQL pool if needed.
Setup SQLPool01
Invoke-Sqlcmd: /home/arvind/Synapse-MCW1/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:979
Line |
 979 |  …   $result = Invoke-SqlCmd -Query $SQLQuery -ConnectionString $sqlConn …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The server principal 'asa.sql.workload01' already exists. The server principal 'asa.sql.workload02' already exists.   Msg 15025, Level 16, State 1, Procedure , Line 1.

Invoke-Sqlcmd: /home/arvind/Synapse-MCW1/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:979
Line |
 979 |  …   $result = Invoke-SqlCmd -Query $SQLQuery -ConnectionString $sqlConn …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | There is already a master key in the database. Please drop it before performing this statement.   Msg 15578, Level 16, State 1, Procedure , Line 1._

**Comment by codingbandit** [comment]
@arvind-dhariwal - it looks like the script has been run more than once. You will not see data in those tables initially.

**Comment by arvind-dhariwal** [comment]
@codingbandit Empty table is expected behavior? and also I don't see SQL scripts for row, column level and dynamic data masking etc. Is that expected behavior?

**Comment by codingbandit** [comment]
Please delete the resource group and restart the lab from the beginning. As mentioned in the other ticket, it looks as if the script was run or partially run previously.

**Comment by DawnmarieDesJardins** [comment]
Updated assignments for visibility

**Comment by timahenning** [comment]
Hi @arvind-dhariwal,

Are there any updates on this issue?

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further correspondence from field.  Please reopen if necessary.
