### ISSUE TITLE
Issue in Exercise 3

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#51]
In exercise 3, task 2, step 1, when selecting **New Notebook** getting it's asking to select from **Load to DataFrame** and **New Spark table**.

![newnotebook-issue](https://user-images.githubusercontent.com/66515706/98706522-f069b400-23a4-11eb-8cdf-3fabe6849920.png)

Exercise 3, task 2, step 6  got an error while running data_path.printSchema() command.  It worked with df.printschema() 

![MicrosoftTeams-image (37)](https://user-images.githubusercontent.com/66515706/98707514-222f4a80-23a6-11eb-8881-09744808743a.png)

**Comment by codingbandit** [comment]
I will verify and get that updated, thank you!

**Comment by codingbandit** [comment]
Thank you, I have updated the screenshot with the new flow, and updated the code listing to reflect the new generated code from Synapse. Thank you for reporting the change :) The fix will be in the next PR.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #53
