### ISSUE TITLE
Issue:Exercise 5-Task3

### ISSUE THREAD

**Issue by Katelyn98098** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#52]
Encountered msg below while publish function in VSCode.
![image](https://user-images.githubusercontent.com/74286744/98776009-8ba86b00-2431-11eb-98a9-94ca4c4d0a3e.png)
![image](https://user-images.githubusercontent.com/74286744/98776076-a5e24900-2431-11eb-87eb-db335d635bb7.png)
Do I need to create a new project?

4 of services are published. 
![image](https://user-images.githubusercontent.com/74286744/98776137-beeafa00-2431-11eb-82ae-0d370560549e.png)
However, unable to fine the GetInvoiceData in Function. I assume that its because of the error above.
![image](https://user-images.githubusercontent.com/74286744/98776218-dd50f580-2431-11eb-9978-5efaa3e23a04.png)

What shoud I do more?

**Comment by codingbandit** [comment]
Hi @Katelyn98098 - In the instructions it says to open a new instance of Visual Studio code. You can choose "Open folder' from the welcome screen, or File -> Open folder, then select the folder Hands-on lab/environment-setup/functions. This way the functions folder will be the root (which is already a functions project) and you shouldn't see those messages and the lab will behave appropriately. From the screenshot above, the functions folder isn't at the root, so your VS Code is open to another folder.

**Comment by Katelyn98098** [comment]
Hi @codingbandit 
It's resolved! 👍
