### ISSUE TITLE
Indexer: Could not execute skill because Web Api skill response is invalid (exercise 5, task 3.22)

### ISSUE THREAD

**Issue by davidaascorreia** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#55]
![image](https://user-images.githubusercontent.com/47411958/99240711-25d72d00-27fd-11eb-80a2-72a0a266d9bc.png)

Previous steps have been successful and I get status 201 for all 4 API calls in the collection "Create a KnowledgeStore".
Still running into this error for the indexer.

**Comment by codingbandit** [comment]
Hi David, could you delete the indexer, and re-run the create indexer from postman ensuring the content-type is set to application/json ? The error is indicating text/plain was passed in.

**Comment by davidaascorreia** [comment]
Hi.

I have tried that. I have also tried deleting all entities (index, data source, skillset and indexer) and recreating it. I have also checked that all pre-configured headers for content-type is set as "application/json". 

Can it be from earlier steps?

**Comment by codingbandit** [comment]
I'll try running through them again and see if I can reproduce.

**Comment by codingbandit** [comment]
Hi David, unfortunately I wasn't able to reproduce. We can approach this a couple of different ways. I can make a recording of the actions that I took for exercise 5 up to the point where you encountered your error. Alternatively, if you could remove all created assets from exercise 5, and I will outline a few things to look for at certain steps.  If you go for the latter, please delete the cognitive service, the search service, and the azure function/resource group entirely.

Areas too look out for:

Task 1, steps 6-11. We have seen in the past some browsers be finicky with the Storage Explorer. Please verify that the invoices container has a Test and Train folder. The Test folder will have invoices 6 and 7, and the Train folder should have invoices 1 through 5.

Task 1, step 15. Give your SAS token a longer duration by increasing the end date, sometimes the lab isn't completed in one sitting and the SAS URL can expire.

Task 1, step 17, This is one that seems to get overlooked from time to time, ensure you inject the text "invoices" to the SAS url that was created (before the ? character)

Task 2, step 16, be sure to use the Form Recognizer service secrets (not the cognitive search)

Task 2, step 20, When this runs, it shouldn't return immediately, please make sure in the text directly above the output of the model that you see the text that "Training succeeded" and next to the modelId that the status is "ready" -- if something goes wrong in the training it will not succeed and show a status of invalid, but still output a modelId.

Other than that, in Postman for the variables, just be sure to pay attention if the variable is requesting the Form recognizer service secrets or the cognitive search service.

I also want you to know that not finishing this lab does not stop you from jumping to the next exercise in this lab. So if you want to come back to it later, there is no ill effects from skipping it for now.

Please let me know if you would like a video walkthrough of exercise 5 (up to your error).

**Comment by davidaascorreia** [comment]
It would be nice to have the walkthrough-video. I will then try again later with both the video and the highlighted points you outline above.

Meanwhile I'll just proceed to the next exercise.

Thanks!

**Comment by codingbandit** [comment]
Hi David - here is a recording of exercise 5. I hope this helps! (you may need to download to watch the entire video) :

https://www.dropbox.com/s/ulukbiytx75fw46/SynapseMCWIssue55.mp4?dl=0
