### ISSUE TITLE
Install AzCopy as requirements

### ISSUE THREAD

**Issue by moatwork** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#57]
AzCopy is also needed to run .ps, would be helpful to add it in [Requirments](https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Azure%20Synapse%20Analytics%20and%20AI.md#requirements)
with a reminder: add azcopy.exe to system path and relaunch PowerShell

**Comment by codingbandit** [comment]
@moatwork - The lab indicates to use cloud shell to run the PowerShell scripts. The cloud shell already has AzCopy functionality and no installation is necessary.

**Comment by moatwork** [comment]
ok. Yes. Thanks. for the users using local env, needs to install AzCopy in Win and Install-Module sqlserver in PowerShell.
