### ISSUE TITLE
Task 2: Create the Azure Synapse Analytics workspace | Deployment Failure

### ISSUE THREAD

**Issue by mreherefortea** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#60]
Hello All:
In Before the HOL Task 2: Create the Azure Synapse Analytics workspace, the template runs into a failure due to the subscription needing to be registered with Microsoft. SQL as a resource provider.  To give an example:

![image](https://user-images.githubusercontent.com/41710326/103012062-978f4e80-4500-11eb-99ea-b414f6f40153.png)

this may be good to add some sort of note here or outline steps for registering, before attempting the deployment.

**Comment by codingbandit** [comment]
I will add a note for that, thank you for the information @mreherefortea :)

**Comment by mreherefortea** [comment]
Thank you! :)

**Comment by DawnmarieDesJardins** [comment]
@codingbandit 
Hello, any update for us?  Thank you!

**Comment by codingbandit** [comment]
I'll submit a small PR momentarily

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #62
