### ISSUE TITLE
Before the HOL - Task 5 / Permission Denied

### ISSUE THREAD

**Issue by cyantac** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#61]
While running the Task 5 "Environment Setup", executing the command "./01-environment-setup.ps1" results in a "permission denied" error. 
![HOL-Prep1](https://user-images.githubusercontent.com/29413793/103027057-3732f800-4566-11eb-8e83-76fdcd836dd2.JPG)

**Comment by codingbandit** [comment]
Hi @cyantac , Could you change the cloud shell to Powershell and see if that helps ?

**Comment by cyantac** [comment]
Yes, it does help. Issue resolved.
