### ISSUE TITLE
Improve lab experience/Save time: Very Long load timings for Ex.2/Task 2 (load sales table)

### ISSUE THREAD

**Issue by virshah24** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#64]
This workshop has been working out for our customers very well, but wanted to suggest couple of enhancements to better help manage the lab timings & customer experience about the product.

The sales table load step Ex.2/Task 2 for ~667M rows takes up to 55-60 mins with 200 cDWU & 4+4 General purpose IR, if all goes well :). 
We can probably enhance the lab by either:

> 1. Add a step to scale up to 1000 cDWU, and use 8+8 General Purpose IR will reduce to around 20-25 mins. And add a step to scale down AGAIN - in fact this will show customers practical scenarios (scale up/down) in real life, IMHO.
> 2. Reduce the number of rows to somewhere around 200M to allow the loads to be completed around 20 mins.

**Comment by codingbandit** [comment]
Thank you, @virshah24 ! - for right now we will be adding an additional note clarifying the duration. The environment in the context of the MCW is created at 500 DWU. So while it still takes time, we will make that clear in the text, also indicating how many rows are being processed.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #66
