### ISSUE TITLE
Issue with lab: AutoML Dataset creation times out/fails due to very large sales dataset (Ex.7/Step 9)

### ISSUE THREAD

**Issue by virshah24** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#65]
While creating a dataset for AutoML (Ex.7/Step 9), setting query timeout to 100 doesn't help. I had to change the timeout to 200 and update the SQL Query to add only 1 year to complete the step. Again, this could be a good practical use case where we can use data from 2019 to train, and use data from 2020 to predict, for example.

To fix this I usually ask students to add the WHERE condition, see below, and it works. 

SELECT  P.ProductId,P.Seasonality,S.TransactionDateId,COUNT(*) as TransactionItemsCount
FROM wwi_mcw.SaleSmall S
JOIN wwi_mcw.Product P ON S.ProductId = P.ProductId
**_where TransactionDateId  between 01012019 and 12312019_**
GROUP BY P.ProductId ,P.Seasonality,S.TransactionDateId

**Comment by codingbandit** [comment]
Thank you @virshah24 !

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #66
