### ISSUE TITLE
For next test/fix: Move exercise 5 to the end of the workshop

### ISSUE THREAD

**Issue by codingbandit** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#67]
Renumber impacted exercises
Rename impacted deployment artifacts
Review content for any links/mentions to impacted exercise numbers.

**Comment by DawnmarieDesJardins** [comment]
Labeling issue as an enhancement .

**Comment by codingbandit** [comment]
@DawnmarieDesJardins - this one can be closed now too, I've moved the optional exercises to the end of the HOL
