### ISSUE TITLE
Issue on Exercise 3 Task2

### ISSUE THREAD

**Issue by marcuskk** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#76]
Hi, 

Thank you for the HOL, it was great.
Below is the error when I try to load the parquet to dataset using Spark

NameError: name 'display' is not defined
Traceback (most recent call last):

NameError: name 'display' is not defined

**Comment by marcuskk** [comment]
Exercise 3: Exploring raw parquet
Task 2: Query sales Parquet data with Azure Synapse Spark

I'm using Azure free trial to do so, not sure is it the problem of the free account.

**Comment by joelhulen** [comment]
I've seen this error happen with the versions of libraries referenced in the configuration file for the Spark pool. There is some combination of those pinned versions and the current default versions the Spark pool loads. If you create a brand new Spark pool without a configuration file defined, does the `display` method work?

**Comment by marcuskk** [comment]
Yeah it work.
Thank you all.
