### ISSUE TITLE
HOL Exercise 7  Task 4 Step 2, PCAData not mentioned before

### ISSUE THREAD

**Issue by Kele087** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#77]
In HOL Exercise 4: Leverage Automated ML to create and deploy a Product Seasonality Classifier model. Step2,

"In the previous task, we registered our PCA dataframe (named pcadata) to use with Auto ML. Select pcadata from the list and select Next."

Did not see any mention that pcadata is registered.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with no further contact.  Please reopen if needed.
