### ISSUE TITLE
100 DWUs tag for tracking cost

### ISSUE THREAD

**Issue by dfay88** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#79]
I believe as part of the environment setup a tag is created called "100 dwus" which references the dedicated SQL pool. The size of the dedicated SQL pool which is actually created is 500. Can someone please update the tag so that it does not lead to confusion? We ran this workshop with a customer and they were initially very concerned with the pricing being much higher than expected because of that discrepancy. Thanks!

**Comment by biwa7636** [comment]
I was a student part of the training, here is some info that might help.

It looks like the DW500c SKU was configured in 00-asa-workspace-core.json, but the tag "100 dwus" couldn't be found anywhere inside the git repo, curious who it got tagged inside Synapse to be 100 in the first place. 

![image](https://user-images.githubusercontent.com/3793823/120840306-48c1f800-c527-11eb-8d02-47985fc14589.png)

**Comment by codingbandit** [comment]
I just went through the deployment, the SQL Pool doesn't have any tags associated with it. 
![image](https://user-images.githubusercontent.com/3979478/121915943-af060200-cd01-11eb-88e5-706addb8403c.png)

**Comment by timahenning** [comment]
I have not seen any responses on this issue in 4 days.  Can I close this issue?

**Comment by DawnmarieDesJardins** [comment]
No further field communication, closing issue.  Please reopen if needed.
