### ISSUE TITLE
Exercise 6 - Task 3: Making predictions with the registered models.

### ISSUE THREAD

**Issue by ashumedi** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#8]
This is regarding the Exercise 6 - Task 3: Making predictions with the registered models. On Synapse we are not able to run the Predict function and its giving Model is not recognized.  What could be the issue internal teams pointed out 

If you running in Synapse, it needs to be whitelisted and the whitelisting is being opened across the regions. For other SQL environments, ONNX runtime is only supported in SQL Managed Instance and SQL Edge at this time. Please refer to this doc here. 
https://docs.microsoft.com/en-us/sql/t-sql/queries/predict-transact-sql?view=sql-server-ver15

Request you to provide some input

5. Create another new SQL script and replace the contents with the following:

-- Retrieve the latest hex encoded ONNX model from the table
DECLARE @model varbinary(max) = (SELECT Model FROM [wwi_mcw].[ASAMCWMLModel] WHERE Id = (SELECT Top(1) max(ID) FROM [wwi_mcw].[ASAMCWMLModel]));

-- Run a prediction query
SELECT d.*, p.*
FROM PREDICT(MODEL = @model, DATA = [wwi_mcw].[ProductPCA] AS d) WITH (prediction real) AS p;

**###Error: Failed to execute query. Error: Parse error at line: 26, column: 14: Incorrect syntax near 'MODEL'.**

**Comment by codingbandit** [comment]
@ashumedi - thank you for the observation. It has been determined in order to make use of the `PREDICT` T-SQL function, your environment will need to be whitelisted. If your environment is not whitelisted, then you should read through the steps of this task as a reference as you will not be able to run the prediction queries. I have added such a note to the Task and it will be included in the next PR.

**Comment by rawatsudhir1** [comment]
I am also getting the same error.

Failed to execute query. Error: Incorrect syntax near '='. Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

Where can i request for whitelist ?

**Comment by ambar265** [comment]
can I have instructions to whitelist Synapse SQL (internal MS subscription) for ONNX support

**Comment by Sneha1085** [comment]
Getting an error Incorrect Syntax near 'Model' while running the Prediction function in T-SQL statement. The below query was tried on Azure Synapse Studio as well SSMS and did not work


DECLARE @modelvarbinary(max) = (SELECT Model FROM [wwi_mcw].[ASAMCWMLModel] WHERE Id = (SELECT Top(1) max(ID)
FROM [wwi_mcw].[ASAMCWMLModel]));


Select d.,p. from PREDICT(MODEL=@model,DATA=[wwi_mcw].[ProductPCA]as d) WITH(prediction real)as p;


GitHub link Referenced for the above example: https://github.com/microsoft/MCW-Azure-Synapse-Analytics-end-to-end-solution

**Comment by codingbandit** [comment]
@DawnmarieDesJardins this one can be closed, we have removed this part of the lab until PREDICT is better supported.

**Comment by DawnmarieDesJardins** [comment]
Closing issue
