### ISSUE TITLE
Lab Guide Updates

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#82]
1. In Exercise 2, task 4(instruction 6) and task 6(instruction 7), While adding new integration dataset to synapse workspace, the dataset name has been changed from Azure Synapse Analytics (formerly SQL DW) to Azure Synapse Analytics.  Both screenshot and instruction has to be updated.
2. The same thing has to be changed in Exercise 5, task 4(instruction 33), the resource looks like as shown in the below image.

![issue2](https://user-images.githubusercontent.com/83349665/123789670-0b207700-d8fb-11eb-981e-14854270e51b.png)

3. In Exercise 2, task 2(instruction 14 & 17) and task 6(instruction 13), While creating data flows, For selecting source type and sink type in source settings there are 2 options for the datasets as shown in the below image. Both instruction and Screenshot has to be updated.

![issue1](https://user-images.githubusercontent.com/83349665/123790359-dbbe3a00-d8fb-11eb-91a6-da9d63829322.png)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #83
