### ISSUE TITLE
October 2021 suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#84]

**Comment by timahenning** [comment]
- update screenshots for UI changes/updates
- update spark pool to use 3.1
- mention and explain TTL for dataflows
- the machine learning exercise to be revamped to be "Synapse first". Use the integrations available within Synapse Studio vs. having them new exercise using Cognitive Services wizard
- all centered around Azure Machine Learning Studio
- new exercise GitHub actions (Synapse workspace deployment) - probably make this one optional
- re-arrange exercises so optional exercises are found the end of the HOL

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #88
