### ISSUE TITLE
Issue connecting dedicated sql pool as AML datastore

### ISSUE THREAD

**Issue by dfay88** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#87]
I am running this as a workshop with a customer and we are not able to create a datastore from the dedicated sql pool in Synapse. In the server name drop down nothing pops up. When I check the documentation for Azure Machine Learning Synapse is not listed as a supported datastore.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #88
