### ISSUE TITLE
storage container wwi-02 is missing the parquet files.

### ISSUE THREAD

**Issue by luckypamula** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#91]
I have completed the necessary Before the HOL steps and running the SQL script to populate the SalesSmall table (HOL Task 1, Step 3). But the Blob container wwi-02 is missing the parquet files.

**Comment by codingbandit** [comment]
Hi @luckypamula - I just went through the before the hands-on lab setup and was unable to recreate the issue. Some things to look into is 1) make sure the deployment completes before performing the cloud shell steps 2) ensure you use the cloud shell when running the powershell script 3) ensure the environment validation succeeds with the powershell script

![image](https://user-images.githubusercontent.com/3979478/144450887-a9551136-ad53-473c-b7e9-219d7ebeaf4a.png)

**Comment by DawnmarieDesJardins** [comment]
No additional comments, closing issue.  Please reopen if you're still having trouble.
