### ISSUE TITLE
Represent the content in a web application

### ISSUE THREAD

**Issue by rawatsudhir1** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#92]
Hi Team,

It's not an issue but a general question. Can someone present this content in a web application? The idea is to make more user friendly for the attendees.

**Comment by DawnmarieDesJardins** [comment]
@rawatsudhir1 
Thanks for the question!  If you go to the Code tab from this page and look for HTMLLINKS.md on the front page.  Is that what you're looking for?

**Comment by aschip** [comment]
Hi @DawnmarieDesJardins , what we are looking to do is present the content within the HOL markdown files in a more user friendly manner on a separate static web application hosted by us & co-branded with Microsoft.

**Comment by DawnmarieDesJardins** [comment]
Thanks for the clarification!  

We create and maintain the content, but do not deliver workshops.  CloudLabs, by Spektra, does create and host lab environments for all our MCWs. They would be the next best step for you.  

Try this link: https://cloudlabs.ai

**Comment by aschip** [comment]
@DawnmarieDesJardins  I don't think we were clear enough in framing the question. We are not asking about hosting lab environments.  We are asking about actual content in the markdown files.

So how the "HTMLLINKS.md" you shared is displaying what's in markdown files as HTML, similarly a static web app which shows the markdown content as html but in a more user friendly way.

**Comment by DawnmarieDesJardins** [comment]
@aschip - Hello.  This format is the only we provide.  The other option would be to have you download the content and make the changes you'd like.
