### ISSUE TITLE
Exercise 8 task 2 step 18 - train form recognizer with invoice training samples - Error "No valid blobs found in the specified Azure blob container. Please conform to the document format/size/page/dimensions requirements."

### ISSUE THREAD

**Issue by corticalstack** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#94]
Hi,

Exercise 8 task 2 step 18 that trains form recognizer with sample invoices fails with error _"No valid blobs found in the specified Azure blob container. Please conform to the document format/size/page/dimensions requirements."_

I have ensured both the full path url to the container within the storage account, and SAS token, is correct.

Incidentally, if I have the forms from the AI-102 learning (in .jpg), the model trains successfully.

https://microsoftlearning.github.io/AI-102-AIEngineer/Instructions/21-form-recognizer.html

A compatibility issue with latest form recognizer and the sample invoices provided by this workshop?

Many thanks.

**Comment by corticalstack** [comment]
@codingbandit thanks for the feedback, will retest in next days and edit this with results

**Comment by DawnmarieDesJardins** [comment]
@corticalstack 
Hello!  Please let us know if we can close this issue.
