### ISSUE TITLE
Secret scanning alerts

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#95]
Received these two notices today.  Please review and advise.  
Close as options are Revoked, False positive, Used in tests, and Won't fix

Security main page:
![image](https://user-images.githubusercontent.com/39317565/170114994-3d2cf283-6558-4225-9d03-435b0d7e0205.png)

Individual shots:  Azure Storage Account Access Key 1
![image](https://user-images.githubusercontent.com/39317565/170115585-a34e2e6a-afcc-4386-b03f-e669bb707fc5.png)

Individual shots:  Azure Storage Account Access Key 2
![image](https://user-images.githubusercontent.com/39317565/170115357-22b3b069-0ba0-4988-9172-4c25a4b0a131.png)

Thank you

**Comment by codingbandit** [comment]
Hi Dawnmarie, I've verified and these are all for older commits, these storage accounts/search resources don't exist any longer, therefore the keys are not valid anyhow. These can be flagged as "Won't Fix".

**Comment by DawnmarieDesJardins** [comment]
Done, thanks Carey!  Closing issue as resolved.
