### ISSUE TITLE
Suddenly, the arm template doesn't work 

### ISSUE THREAD

**Issue by Katelyn98098s** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#96]
It was able to deploy resources through the arm template a few hours ago, but suddenly it shows the error msg 'Could not create the marketplace item' 
Can anyone help on this?

[Address] Before the hands-on lab> Task 2: Create the Azure Synapse Analytics workspace> 1. Deploy the workspace through the following Azure ARM template (press the button below):

https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Azure%20Synapse%20Analytics%20and%20AI.md#task-2-create-the-azure-synapse-analytics-workspace

**Comment by codingbandit** [comment]
Hi @Katelyn98098s - I apologize you had problems deploying the resources. It must have been a transitive problem as I am able to deploy successfully with the ARM template (in the East US region). Please remove all resources and attempt to redeploy.

![image](https://user-images.githubusercontent.com/3979478/174791144-e26639ee-6184-4838-9426-c6da797b49e0.png)

**Comment by DawnmarieDesJardins** [comment]
@Katelyn98098s - Hello!  Checking back in to see if you were able to complete the arm template with the suggestions above.

**Comment by DawnmarieDesJardins** [comment]
No additional contact, closing issue.  If you find you're still having trouble, please comment and reopen.
