### ISSUE TITLE
Azure Synapse Integration Dataset in Step failed to get KeyVault secret in Exercise 2 Task 2 of Hands on Lab

### ISSUE THREAD

**Issue by DariusElliott** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#99]
I know this is getting deprecated soon, and this is such a good lab. But is there anyway to grant access to from the Azure Synapse workplace to access the tables? I am getting an error message like the following: 

"Schema import failed: Failed to get the secret from key vault, secretName: SQL-USER-ASA, secretVersion: , vaultBaseUrl: https://asakeyvaultde1992.vault.azure.net/. The error message is: A secret with (name/id) SQL-USER-ASA was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182.\r\n Activity ID: e897c824-dce5-41b3-acc3-5b1600c52905"

**Comment by DawnmarieDesJardins** [comment]
@DariusElliott @codingbandit 
Hi Darius!  Since this is being archived this week, we don't have bandwidth to investigate a fix.  I'm looping our author to see if she has a quick bit of advice for you though.  Hopefully it's something easy.

**Comment by DariusElliott** [comment]
Thank you!

I understand these are wonderful labs you wouldn’t happen to know where a comprehensive lab like this would be else where would you? I find that MSLearn isn’t super extensive.

Darius Elliott

**Comment by DawnmarieDesJardins** [comment]
@DariusElliott - Hi Darius!  I reached out to some of our Data & AI folks and got additional training links for you to look at.  I'll send those along via email.

**Comment by DawnmarieDesJardins** [comment]
Closing issue to archive content.
